---
- name: Update service with command node
  become: true
  template:
    src: node-service.j2
    dest: /etc/systemd/system/inescoin-node.service
    mode: 0644
    owner: '{{ service.node.owner }}'
    group: '{{ service.node.group }}'

- name: Start inescoin-node.service
  systemd:
    name: inescoin-node.service
    state: restarted
    daemon_reload: yes
