---
- assert:
    msg: "OS must be based on Debian"
    that:
      - ansible_os_family == 'Debian'

- name: Add PHP 7 PPA repository
  become: true
  apt_repository:
    repo: 'ppa:ondrej/php'

- apt:
    update_cache: yes

- name: Install dependencies
  become: true
  apt:
    name: "{{ packages }}"
    install_recommends: no
  vars:
    packages:
      - php7.3-cli
      - php7.3-json
      - php7.3-curl
      - php7.3-fpm
      - php7.3-gd
      - php7.3-gmp
      - php7.3-ldap
      - php7.3-mbstring
      - php7.3-mysql
      - php7.3-soap
      - php7.3-sqlite3
      - php7.3-xml
      - php7.3-zip
      - php7.3-intl
      - php-imagick
      - php-pear
      - php7.3-dev
      - openssl
      - nano
      - graphicsmagick
      - imagemagick
      - ghostscript
      - mysql-client
      - iputils-ping
      - locales
      - ca-certificates
      - libxml2-dev

- apt:
    autoclean: yes
  become: true

- apt:
    autoremove: yes
  become: true
